spring:
  main:
    banner-mode: off
  application:
    name: ${SPRING_APPLICATION_NAME:service-registry}

server:
  port: ${SERVER_PORT:8761}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus