/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.walkway.kafka_events.product_item_events;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Product Item Lifecycle events */
@org.apache.avro.specific.AvroGenerated
public class ProductItemEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8678659752135300320L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProductItemEvent\",\"namespace\":\"com.walkway.kafka_events.product_item_events\",\"doc\":\"Product Item Lifecycle events\",\"fields\":[{\"name\":\"eventType\",\"type\":{\"type\":\"enum\",\"name\":\"ProductItemEventType\",\"symbols\":[\"CREATED\",\"DELETED\"]},\"doc\":\"Type of the product item event\"},{\"name\":\"payload\",\"type\":[{\"type\":\"record\",\"name\":\"ProductItemCreatedEvent\",\"doc\":\"A new product item was created\",\"fields\":[{\"name\":\"productItemCode\",\"type\":\"int\"}]},{\"type\":\"record\",\"name\":\"ProductItemDeletedEvent\",\"doc\":\"A product item was deleted\",\"fields\":[{\"name\":\"productItemCode\",\"type\":\"int\"}]}],\"doc\":\"The different product item events\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ProductItemEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ProductItemEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ProductItemEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ProductItemEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ProductItemEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ProductItemEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ProductItemEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ProductItemEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ProductItemEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Type of the product item event */
  private com.walkway.kafka_events.product_item_events.ProductItemEventType eventType;
  /** The different product item events */
  private java.lang.Object payload;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ProductItemEvent() {}

  /**
   * All-args constructor.
   * @param eventType Type of the product item event
   * @param payload The different product item events
   */
  public ProductItemEvent(com.walkway.kafka_events.product_item_events.ProductItemEventType eventType, java.lang.Object payload) {
    this.eventType = eventType;
    this.payload = payload;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return eventType;
    case 1: return payload;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: eventType = (com.walkway.kafka_events.product_item_events.ProductItemEventType)value$; break;
    case 1: payload = value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'eventType' field.
   * @return Type of the product item event
   */
  public com.walkway.kafka_events.product_item_events.ProductItemEventType getEventType() {
    return eventType;
  }


  /**
   * Sets the value of the 'eventType' field.
   * Type of the product item event
   * @param value the value to set.
   */
  public void setEventType(com.walkway.kafka_events.product_item_events.ProductItemEventType value) {
    this.eventType = value;
  }

  /**
   * Gets the value of the 'payload' field.
   * @return The different product item events
   */
  public java.lang.Object getPayload() {
    return payload;
  }


  /**
   * Sets the value of the 'payload' field.
   * The different product item events
   * @param value the value to set.
   */
  public void setPayload(java.lang.Object value) {
    this.payload = value;
  }

  /**
   * Creates a new ProductItemEvent RecordBuilder.
   * @return A new ProductItemEvent RecordBuilder
   */
  public static com.walkway.kafka_events.product_item_events.ProductItemEvent.Builder newBuilder() {
    return new com.walkway.kafka_events.product_item_events.ProductItemEvent.Builder();
  }

  /**
   * Creates a new ProductItemEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ProductItemEvent RecordBuilder
   */
  public static com.walkway.kafka_events.product_item_events.ProductItemEvent.Builder newBuilder(com.walkway.kafka_events.product_item_events.ProductItemEvent.Builder other) {
    if (other == null) {
      return new com.walkway.kafka_events.product_item_events.ProductItemEvent.Builder();
    } else {
      return new com.walkway.kafka_events.product_item_events.ProductItemEvent.Builder(other);
    }
  }

  /**
   * Creates a new ProductItemEvent RecordBuilder by copying an existing ProductItemEvent instance.
   * @param other The existing instance to copy.
   * @return A new ProductItemEvent RecordBuilder
   */
  public static com.walkway.kafka_events.product_item_events.ProductItemEvent.Builder newBuilder(com.walkway.kafka_events.product_item_events.ProductItemEvent other) {
    if (other == null) {
      return new com.walkway.kafka_events.product_item_events.ProductItemEvent.Builder();
    } else {
      return new com.walkway.kafka_events.product_item_events.ProductItemEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for ProductItemEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProductItemEvent>
    implements org.apache.avro.data.RecordBuilder<ProductItemEvent> {

    /** Type of the product item event */
    private com.walkway.kafka_events.product_item_events.ProductItemEventType eventType;
    /** The different product item events */
    private java.lang.Object payload;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.walkway.kafka_events.product_item_events.ProductItemEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.eventType)) {
        this.eventType = data().deepCopy(fields()[0].schema(), other.eventType);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.payload)) {
        this.payload = data().deepCopy(fields()[1].schema(), other.payload);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing ProductItemEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.walkway.kafka_events.product_item_events.ProductItemEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.eventType)) {
        this.eventType = data().deepCopy(fields()[0].schema(), other.eventType);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.payload)) {
        this.payload = data().deepCopy(fields()[1].schema(), other.payload);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'eventType' field.
      * Type of the product item event
      * @return The value.
      */
    public com.walkway.kafka_events.product_item_events.ProductItemEventType getEventType() {
      return eventType;
    }


    /**
      * Sets the value of the 'eventType' field.
      * Type of the product item event
      * @param value The value of 'eventType'.
      * @return This builder.
      */
    public com.walkway.kafka_events.product_item_events.ProductItemEvent.Builder setEventType(com.walkway.kafka_events.product_item_events.ProductItemEventType value) {
      validate(fields()[0], value);
      this.eventType = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'eventType' field has been set.
      * Type of the product item event
      * @return True if the 'eventType' field has been set, false otherwise.
      */
    public boolean hasEventType() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'eventType' field.
      * Type of the product item event
      * @return This builder.
      */
    public com.walkway.kafka_events.product_item_events.ProductItemEvent.Builder clearEventType() {
      eventType = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'payload' field.
      * The different product item events
      * @return The value.
      */
    public java.lang.Object getPayload() {
      return payload;
    }


    /**
      * Sets the value of the 'payload' field.
      * The different product item events
      * @param value The value of 'payload'.
      * @return This builder.
      */
    public com.walkway.kafka_events.product_item_events.ProductItemEvent.Builder setPayload(java.lang.Object value) {
      validate(fields()[1], value);
      this.payload = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'payload' field has been set.
      * The different product item events
      * @return True if the 'payload' field has been set, false otherwise.
      */
    public boolean hasPayload() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'payload' field.
      * The different product item events
      * @return This builder.
      */
    public com.walkway.kafka_events.product_item_events.ProductItemEvent.Builder clearPayload() {
      payload = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ProductItemEvent build() {
      try {
        ProductItemEvent record = new ProductItemEvent();
        record.eventType = fieldSetFlags()[0] ? this.eventType : (com.walkway.kafka_events.product_item_events.ProductItemEventType) defaultValue(fields()[0]);
        record.payload = fieldSetFlags()[1] ? this.payload :  defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ProductItemEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<ProductItemEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ProductItemEvent>
    READER$ = (org.apache.avro.io.DatumReader<ProductItemEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










