/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.walkway.kafka_events.product_item_events;
@org.apache.avro.specific.AvroGenerated
public enum ProductItemEventType implements org.apache.avro.generic.GenericEnumSymbol<ProductItemEventType> {
  CREATED, DELETED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ProductItemEventType\",\"namespace\":\"com.walkway.kafka_events.product_item_events\",\"symbols\":[\"CREATED\",\"DELETED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
