/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.walkway.kafka_events.product_item_events;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** A new product item was created */
@org.apache.avro.specific.AvroGenerated
public class ProductItemCreatedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1770489849702291938L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProductItemCreatedEvent\",\"namespace\":\"com.walkway.kafka_events.product_item_events\",\"doc\":\"A new product item was created\",\"fields\":[{\"name\":\"productItemCode\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ProductItemCreatedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ProductItemCreatedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ProductItemCreatedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ProductItemCreatedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ProductItemCreatedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ProductItemCreatedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ProductItemCreatedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ProductItemCreatedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ProductItemCreatedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int productItemCode;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ProductItemCreatedEvent() {}

  /**
   * All-args constructor.
   * @param productItemCode The new value for productItemCode
   */
  public ProductItemCreatedEvent(java.lang.Integer productItemCode) {
    this.productItemCode = productItemCode;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return productItemCode;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: productItemCode = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'productItemCode' field.
   * @return The value of the 'productItemCode' field.
   */
  public int getProductItemCode() {
    return productItemCode;
  }


  /**
   * Sets the value of the 'productItemCode' field.
   * @param value the value to set.
   */
  public void setProductItemCode(int value) {
    this.productItemCode = value;
  }

  /**
   * Creates a new ProductItemCreatedEvent RecordBuilder.
   * @return A new ProductItemCreatedEvent RecordBuilder
   */
  public static com.walkway.kafka_events.product_item_events.ProductItemCreatedEvent.Builder newBuilder() {
    return new com.walkway.kafka_events.product_item_events.ProductItemCreatedEvent.Builder();
  }

  /**
   * Creates a new ProductItemCreatedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ProductItemCreatedEvent RecordBuilder
   */
  public static com.walkway.kafka_events.product_item_events.ProductItemCreatedEvent.Builder newBuilder(com.walkway.kafka_events.product_item_events.ProductItemCreatedEvent.Builder other) {
    if (other == null) {
      return new com.walkway.kafka_events.product_item_events.ProductItemCreatedEvent.Builder();
    } else {
      return new com.walkway.kafka_events.product_item_events.ProductItemCreatedEvent.Builder(other);
    }
  }

  /**
   * Creates a new ProductItemCreatedEvent RecordBuilder by copying an existing ProductItemCreatedEvent instance.
   * @param other The existing instance to copy.
   * @return A new ProductItemCreatedEvent RecordBuilder
   */
  public static com.walkway.kafka_events.product_item_events.ProductItemCreatedEvent.Builder newBuilder(com.walkway.kafka_events.product_item_events.ProductItemCreatedEvent other) {
    if (other == null) {
      return new com.walkway.kafka_events.product_item_events.ProductItemCreatedEvent.Builder();
    } else {
      return new com.walkway.kafka_events.product_item_events.ProductItemCreatedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for ProductItemCreatedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProductItemCreatedEvent>
    implements org.apache.avro.data.RecordBuilder<ProductItemCreatedEvent> {

    private int productItemCode;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.walkway.kafka_events.product_item_events.ProductItemCreatedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.productItemCode)) {
        this.productItemCode = data().deepCopy(fields()[0].schema(), other.productItemCode);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing ProductItemCreatedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.walkway.kafka_events.product_item_events.ProductItemCreatedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.productItemCode)) {
        this.productItemCode = data().deepCopy(fields()[0].schema(), other.productItemCode);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'productItemCode' field.
      * @return The value.
      */
    public int getProductItemCode() {
      return productItemCode;
    }


    /**
      * Sets the value of the 'productItemCode' field.
      * @param value The value of 'productItemCode'.
      * @return This builder.
      */
    public com.walkway.kafka_events.product_item_events.ProductItemCreatedEvent.Builder setProductItemCode(int value) {
      validate(fields()[0], value);
      this.productItemCode = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'productItemCode' field has been set.
      * @return True if the 'productItemCode' field has been set, false otherwise.
      */
    public boolean hasProductItemCode() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'productItemCode' field.
      * @return This builder.
      */
    public com.walkway.kafka_events.product_item_events.ProductItemCreatedEvent.Builder clearProductItemCode() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ProductItemCreatedEvent build() {
      try {
        ProductItemCreatedEvent record = new ProductItemCreatedEvent();
        record.productItemCode = fieldSetFlags()[0] ? this.productItemCode : (java.lang.Integer) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ProductItemCreatedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<ProductItemCreatedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ProductItemCreatedEvent>
    READER$ = (org.apache.avro.io.DatumReader<ProductItemCreatedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.productItemCode);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.productItemCode = in.readInt();

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.productItemCode = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










